version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  practice-function:
    lang: python3-http
    handler: ./practice-function
    image: docker.io/elhanbthomas/practice-function:latest

